In [28]:
import numpy as np
import pandas as pd

In [29]:
# load datasets
nodes = pd.read_csv('http://localhost:8888/tree/data/Nodes.csv')

# Node 1 data
# Latitudes
n1_lats = np.round([nodes['LAT1'][0], nodes['LAT1'][1], nodes['LAT1'][2]], 6)

# Longitudes
n1_lngs = np.round([nodes['LON1'][0], nodes['LON1'][1],nodes['LON1'][2]], 6)

# Node 2 data
# Latitudes
n2_lats = np.round([nodes['LAT2'][0], nodes['LAT2'][1], nodes['LAT2'][2]], 6)

# Longitudes
n2_lngs = np.round([nodes['LON2'][0], nodes['LON2'][1], nodes['LON2'][2]], 6)

# Node 3 data
# Latitudes
n3_lats = np.round([nodes['LAT3'][0], nodes['LAT3'][1], nodes['LAT3'][2]], 6)

# Longitudes
n3_lngs = np.round([nodes['LON3'][0], nodes['LON3'][1], nodes['LON3'][2]], 6)

# Node 4 data
# Latitudes
n4_lats = np.round([nodes['LAT4'][0], nodes['LAT4'][1], nodes['LAT4'][2]], 6)

# Longitudes
n4_lngs = np.round([nodes['LON4'][0], nodes['LON4'][1], nodes['LON4'][2]], 6)

In [32]:
import gmplot

# Singapore lat/lon 1.290270, 103.851959
gmap = gmplot.GoogleMapPlotter(1.290270, 103.851959, 12)

# plot Node 1
gmap.plot(n1_lats, n1_lngs, 'cornflowerblue', edge_width=5) # lines
gmap.scatter(n1_lats, n1_lngs, 'k', size=100, marker=False) # points

# plot Node 2
gmap.plot(n2_lats, n2_lngs, 'cornflowerblue', edge_width=5) # lines
gmap.scatter(n2_lats, n2_lngs, 'k', size=100, marker=False) # points

# plot Node 3
gmap.plot(n3_lats, n3_lngs, 'cornflowerblue', edge_width=5) # lines
gmap.scatter(n3_lats, n3_lngs, 'k', size=100, marker=False) # points

# plot Node 4
gmap.plot(n4_lats, n4_lngs, 'cornflowerblue', edge_width=5) # lines
gmap.scatter(n4_lats, n4_lngs, 'k', size=100, marker=False) # points

# gmap.scatter(marker_lats, marker_lngs, 'k', marker=True)
# gmap.heatmap(heat_lats, heat_lngs)

gmap.draw("mymap.html")

In [21]:
# load prediction 1
prediction = pd.read_csv('http://localhost:8888/tree/data/found.csv')
prediction

,Unnamed: 0,PERIOD,NODE4,LAT4,LON4,NODE1,LAT1,LON1,MA1,DIST1,NODE2,LAT2,LON2,MA2,DIST2,NODE3,LAT3,LON3,MA3,DIST3
0,0,1,CCK,1.385351,103.745053,STN,1.351944,103.765833,9.351852,4.376,YIS,1.423272,103.844975,-19,11.885,BIS,1.359603,103.843286,-13,11.293
1,1,11,CCK,1.390096,103.745582,STN,1.351944,103.765833,3.290909,4.950,YIS,1.425059,103.849078,-21,12.148,BIS,1.364013,103.844911,-14,11.420
2,2,21,CCK,1.400050,103.748157,STN,1.351944,103.765833,1.545455,5.720,YIS,1.424709,103.857244,-22,12.436,BIS,1.371274,103.844609,-12,11.193
3,3,31,CCK,1.398730,103.747135,STN,1.351944,103.765833,0.100000,5.550,YIS,1.424709,103.857244,-25,12.462,BIS,1.371274,103.844609,-13,11.290

In [22]:
# plot predicted Node 4 location
pred_n4_lats = [n4_lats[2], prediction['LAT4'][3]]
pred_n4_lngs = [n4_lngs[2], prediction['LON4'][3]]

gmap.plot(pred_n4_lats, pred_n4_lngs, 'green', edge_width=5) # lines
gmap.scatter(pred_n4_lats, pred_n4_lngs, 'c', size=25, marker=False) # points

gmap.draw("mymap.html")

In [23]:
# load prediction 2
prediction = pd.read_csv('http://localhost:8888/tree/data/found_2.csv')
prediction

,Unnamed: 0,PERIOD,NODE4,LAT4,LON4,NODE1,LAT1,LON1,MA1,DIST1,NODE2,LAT2,LON2,MA2,DIST2,NODE3,LAT3,LON3,MA3,DIST3
0,0,1,CCK,1.385351,103.745053,STN,1.351944,103.765833,9.351852,4.376,YIS,1.423272,103.844975,-19,11.885,BIS,1.359603,103.843286,-13,11.293
1,1,11,CCK,1.390096,103.745582,STN,1.351944,103.765833,3.290909,4.950,YIS,1.425059,103.849078,-21,12.148,BIS,1.364013,103.844911,-14,11.420
2,2,21,CCK,1.400050,103.748157,STN,1.351944,103.765833,1.545455,5.720,YIS,1.424709,103.857244,-22,12.436,BIS,1.371274,103.844609,-12,11.193
3,3,31,CCK,1.398028,103.746671,STN,1.351944,103.765833,0.100000,5.550,YIS,1.424709,103.857244,-25,12.462,BIS,1.371274,103.844609,-13,11.290

In [24]:
# plot predicted Node 4 location
pred_n4_lats = [n4_lats[2], prediction['LAT4'][3]]
pred_n4_lngs = [n4_lngs[2], prediction['LON4'][3]]

gmap.plot(pred_n4_lats, pred_n4_lngs, 'yellow', edge_width=5) # lines
gmap.scatter(pred_n4_lats, pred_n4_lngs, 'gold', size=25, marker=False) # points

gmap.draw("mymap.html")

In [25]:
# load prediction 3
prediction = pd.read_csv('http://localhost:8888/tree/data/found_3.csv')
prediction

,Unnamed: 0,PERIOD,NODE4,LAT4,LON4,NODE1,LAT1,LON1,MA1,DIST1,NODE2,LAT2,LON2,MA2,DIST2,NODE3,LAT3,LON3,MA3,DIST3
0,0,1,CCK,1.385351,103.745053,STN,1.351944,103.765833,9.351852,4.376,YIS,1.423272,103.844975,-19,11.885,BIS,1.359603,103.843286,-13,11.293
1,1,11,CCK,1.390096,103.745582,STN,1.351944,103.765833,3.290909,4.950,YIS,1.425059,103.849078,-21,12.148,BIS,1.364013,103.844911,-14,11.420
2,2,21,CCK,1.400050,103.748157,STN,1.351944,103.765833,1.545455,5.720,YIS,1.424709,103.857244,-22,12.436,BIS,1.371274,103.844609,-12,11.193
3,3,31,CCK,1.401353,103.747659,STN,1.351944,103.765833,0.100000,5.550,YIS,1.424709,103.857244,-25,12.462,BIS,1.371274,103.844609,-13,11.290

In [26]:
# plot predicted Node 4 location
pred_n4_lats = [n4_lats[2], prediction['LAT4'][3]]
pred_n4_lngs = [n4_lngs[2], prediction['LON4'][3]]

gmap.plot(pred_n4_lats, pred_n4_lngs, 'm', edge_width=5) # lines
gmap.scatter(pred_n4_lats, pred_n4_lngs, 'darkviolet', size=25, marker=False) # points

gmap.draw("mymap.html")